# Type
- name: Type:Bug
  color: d93f0b
  description: "Something is broken"

- name: Type:Discussion
  color: bebaf4
  description: "Discussing a topic with no specific actions yet"

- name: Type:Feature
  color: 0052cc
  description: "Something is missing"

- name: Type:Hygiene
  color: bebaf4
  description: "Code quality and project level things"

- name: Type:Testing/CI
  color: f4e49a
  description: "Unit tests and/or continuous integration"

- name: Type:Upstream
  color: 9D7B36
  description: "Relating to upstream libraries"

# Status
- name: Status:Needs Triage
  color: bebaf4
  description: "Awaiting triage"

- name: Status:Needs Attention
  color: e58b7e
  description: "It's been a while since this was pushed on"

- name: Status:Needs Info
  color: bebaf4
  description: "Needs further information"

# Area
- name: Area:Array
  color: 006b75
  description: ""

- name: Area:Bag
  color: 0052cc
  description: ""

- name: Area:Config
  color: 55b3c1
  description: ""

- name: Area:Core
  color: "000000"
  description: ""

- name: Area:Dataframe
  color: fbca04
  description: ""

- name: Area:Delayed
  color: 4f6edd
  description: ""

- name: Area:Documentation
  color: f9d0c4
  description: ""

- name: Area:IO
  color: e99695
  description: ""

- name: Area:Scheduler
  color: 64db8e
  description: ""

- name: Area:Diagnostics/Dashboard
  color: ffcce7
  description: ""

- name: Area:ML
  color: 77dd8d
  description: ""

- name: Area:Deployment
  color: 6eaadd
  description: ""

- name: Area:Networking
  color: c69f03
  description: ""

# Skill level
- name: Experience:Good first Dask issue
  color: "159818"
  description: Clearly described and easy to accomplish. Good for beginners to the project.

- name: Experience:Good second Dask issue
  color: 5319e7
  description: Clearly described, educational, but less trivial than "good first issue".

- name: Experience:Expertise required
  color: db8c72
  description: Needs someone familiar with this area of Dask.

# Priority
- name: Priority:Low
  color: c8ea31
  description: ""

- name: Priority:Medium
  color: f9a6a2
  description: ""

- name: Priority:High
  color: d6043f
  description: ""
