# Type
# uses less saturated colors
- name: bug
  color: faadaf
  description: "Something is broken"

- name: discussion
  color: bebaf4
  description: "Discussing a topic with no specific actions yet"

- name: feature
  color: b0f0fa
  description: "Something is missing"

- name: documentation
  color: f9d0c4
  description: "Improve or add to documentation"

- name: hygiene
  color: b5ccfa
  description: "Improve code quality and reduce maintenance overhead"

- name: deprecation
  color: f4e49a
  description: "Something is being removed"

- name: tests
  color: a0f9b4
  description: "Unit tests and/or continuous integration"

# Status
# prefixed with "needs"
- name: needs attention
  color: 6d626c
  description: "It's been a while since this was pushed on. Needs attention from the owner or a maintainer."

- name: needs review
  color: 8c918c
  description: "Needs review from a contributor."

- name: needs info
  color: d0cfcc
  description: "Needs further information from the user"

# Area
# more saturated colors, projects are encouraged to add many more of these
- name: config
  color: 1586c0
  description: ""

- name: core
  color: "000000"
  description: ""

- name: io
  color: 6f871c
  description: ""

- name: packaging
  color: 03DB41
  description: "Related to packaging infrastructure (e.g. conda, PyPI)"

# Skill level
# prefixed with "good"
- name: good first issue
  color: "159818"
  description: Clearly described and easy to accomplish. Good for beginners to the project.

- name: good second issue
  color: 5319e7
  description: Clearly described, educational, but less trivial than "good first issue".

# Priority
# prefixed with "p" and colors span yellow to red
- name: p3
  color: ffff33
  description: "Affects a small number of users or is largely cosmetic"

- name: p2
  color: ffc133
  description: "Affects more than a few users but doesn't prevent core functions"

- name: p1
  color: ff5233
  description: "Affects a large population and inhibits work"
