# Type
- name: community
  color: d93f0b
  description: ""

- name: discussion
  color: bebaf4
  description: ""

# Area
- name: array
  color: 006b75
  description: ""

- name: bag
  color: 0052cc
  description: ""

- name: config
  color: 55b3c1
  description: ""

- name: core
  color: "000000"
  description: ""

- name: dataframe
  color: fbca04
  description: ""

- name: delayed
  color: 4f6edd
  description: ""

- name: documentation
  color: f9d0c4
  description: ""

- name: io
  color: e99695
  description: ""

- name: scheduler
  color: 64db8e
  description: ""

- name: flaky test
  color: ffcce7
  description: Intermittent failures on CI.

# Skill level
- name: good first issue
  color: "159818"
  description:
    Clearly described and easy to accomplish.  Good for beginners to the
    project

- name: good second issue
  color: 5319e7
  description: Clearly described, educational, but less trivial than "good first issue"

# Status
- name: needs info
  color: f4e49a
  description: ""

- name: stale
  color: D3D3D3
  description: ""

- name: needs triage
  color: 7b9ad8
  description: "Awaiting triage by a Dask Czar."
