---
name: Sync labels in the declarative way (does not delete)
on:
  push:
    branches:
      - main

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    if: github.repository == 'dask/.github'
    strategy:
      matrix:
        repository:
          - dask/dask
          - dask/distributed
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@1.3.0
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repository }}
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          prune: false
