---
name: Sync labels in the declarative way
on:
  push:
    branches:
      - master

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    if: github.repository == 'dask/.github'
    strategy:
      matrix:
        repository:
          - dask/dask
          - dask/distributed
    steps:
      - uses: actions/checkout@v2
      - uses: jacobtomlinson/action-label-syncer@override-repo
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repository }}
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
